# CI for command line NodeJS Applications
name: nodejs
on:
  push:
    paths:
      - '**/**'
      - '!**/*.md/**'

env:
  CI: ''
  FORCE_COLOR: 2

jobs:
  pipeline:
    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node: ['14.x']
        os: ['ubuntu-latest']

    steps:
      - name: Clone repository
        uses: actions/checkout@v2.3.5

      - name: Set up Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: ${{ matrix.node }}
      #          cache: 'yarn'

      - name: Install yarn dependencies
        run: yarn install
        id: install

      - name: Run build
        run: npx next build
        id: build
