# CI for command line NodeJS Applications
name: nextjs
on:
  push:
     paths:
      - "**/**"
      - "!**/*.md/**"

# ensure multiple CI processes are not running analysis on contracts
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true


env:
  CI: ''
  COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
  PULL_NUMBER: ${{ github.event.pull_request.number }}
  RUN_ID: ${{ github.run_id }}
  FORCE_COLOR: 2
  NEXT_TELEMETRY_DISABLED: 1
  NODE_ENV: production


jobs:
  pipeline:
    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node: ['14.x', '16.x']
        os: ['ubuntu-latest']

    steps:
      - name: Clone repository
        uses: actions/checkout@v2.3.5

      - name: Set up Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install npm dependencies
        run: npm install
        id: install

      - name: Run build
        run: npm run build
        id: build